{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d8f4d7ae-bd35-4369-8a3a-fdf3f0f27a66",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in c:\\users\\eliut\\anaconda3\\lib\\site-packages (2.3.3)\n",
      "Requirement already satisfied: numpy in c:\\users\\eliut\\anaconda3\\lib\\site-packages (2.1.3)\n",
      "Requirement already satisfied: scikit-learn in c:\\users\\eliut\\anaconda3\\lib\\site-packages (1.6.1)\n",
      "Collecting fastapi\n",
      "  Downloading fastapi-0.128.0-py3-none-any.whl.metadata (30 kB)\n",
      "Collecting uvicorn\n",
      "  Downloading uvicorn-0.40.0-py3-none-any.whl.metadata (6.7 kB)\n",
      "Requirement already satisfied: joblib in c:\\users\\eliut\\anaconda3\\lib\\site-packages (1.4.2)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: scipy>=1.6.0 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from scikit-learn) (1.15.3)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from scikit-learn) (3.5.0)\n",
      "Collecting starlette<0.51.0,>=0.40.0 (from fastapi)\n",
      "  Downloading starlette-0.50.0-py3-none-any.whl.metadata (6.3 kB)\n",
      "Requirement already satisfied: pydantic>=2.7.0 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from fastapi) (2.10.3)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from fastapi) (4.12.2)\n",
      "Collecting annotated-doc>=0.0.2 (from fastapi)\n",
      "  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)\n",
      "Requirement already satisfied: anyio<5,>=3.6.2 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from starlette<0.51.0,>=0.40.0->fastapi) (4.7.0)\n",
      "Requirement already satisfied: idna>=2.8 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from anyio<5,>=3.6.2->starlette<0.51.0,>=0.40.0->fastapi) (3.7)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from anyio<5,>=3.6.2->starlette<0.51.0,>=0.40.0->fastapi) (1.3.0)\n",
      "Requirement already satisfied: click>=7.0 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from uvicorn) (8.1.8)\n",
      "Requirement already satisfied: h11>=0.8 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from uvicorn) (0.16.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from click>=7.0->uvicorn) (0.4.6)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from pydantic>=2.7.0->fastapi) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.27.1 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from pydantic>=2.7.0->fastapi) (2.27.1)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\eliut\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Downloading fastapi-0.128.0-py3-none-any.whl (103 kB)\n",
      "Downloading starlette-0.50.0-py3-none-any.whl (74 kB)\n",
      "Downloading uvicorn-0.40.0-py3-none-any.whl (68 kB)\n",
      "Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)\n",
      "Installing collected packages: annotated-doc, uvicorn, starlette, fastapi\n",
      "\n",
      "   ---------- ----------------------------- 1/4 [uvicorn]\n",
      "   ---------- ----------------------------- 1/4 [uvicorn]\n",
      "   ---------- ----------------------------- 1/4 [uvicorn]\n",
      "   -------------------- ------------------- 2/4 [starlette]\n",
      "   -------------------- ------------------- 2/4 [starlette]\n",
      "   -------------------- ------------------- 2/4 [starlette]\n",
      "   ------------------------------ --------- 3/4 [fastapi]\n",
      "   ------------------------------ --------- 3/4 [fastapi]\n",
      "   ------------------------------ --------- 3/4 [fastapi]\n",
      "   ------------------------------ --------- 3/4 [fastapi]\n",
      "   ------------------------------ --------- 3/4 [fastapi]\n",
      "   ---------------------------------------- 4/4 [fastapi]\n",
      "\n",
      "Successfully installed annotated-doc-0.0.4 fastapi-0.128.0 starlette-0.50.0 uvicorn-0.40.0\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install pandas numpy scikit-learn fastapi uvicorn joblib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "9ce85293-fd77-493d-ba93-f8fa5b8fa288",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-01-20 15:10:19,858 - EmbarkCore - INFO - Entrenando modelo v1.0.0 con 2000 registros...\n",
      "2026-01-20 15:10:20,294 - EmbarkCore - INFO - Modelo entrenado. Accuracy en test: 1.0000\n",
      "2026-01-20 15:10:20,338 - EmbarkCore - INFO - Modelo guardado en embark_model.pkl\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "¡Proceso de entrenamiento finalizado! Archivo .pkl generado.\n"
     ]
    }
   ],
   "source": [
    "# model_core.py\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import logging\n",
    "from typing import List, Optional\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import classification_report\n",
    "\n",
    "# Configuración de logs profesional\n",
    "logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')\n",
    "logger = logging.getLogger(\"EmbarkCore\")\n",
    "\n",
    "# --- 1. FUNCIÓN DE SIMULACIÓN DE DATOS ---\n",
    "def generar_datos_jugadores(n_jugadores=2000):\n",
    "    \"\"\"Genera datos sintéticos para entrenar el modelo si no hay datos reales.\"\"\"\n",
    "    np.random.seed(42)\n",
    "    data = []\n",
    "    \n",
    "    for _ in range(n_jugadores):\n",
    "        es_cheater = np.random.choice([0, 1], p=[0.90, 0.10])\n",
    "        \n",
    "        if es_cheater:\n",
    "            # Cheater: Reacción rápida, trayectoria perfecta, muchos headshots\n",
    "            time_to_dmg = np.random.normal(loc=150, scale=20) \n",
    "            aim_path_error = np.random.normal(loc=0.5, scale=0.5) \n",
    "            headshot_rate = np.random.normal(loc=0.95, scale=0.05)\n",
    "        else:\n",
    "            # Humano: Reacción lenta, error de mouse, headshots variados\n",
    "            time_to_dmg = np.random.normal(loc=350, scale=80) \n",
    "            aim_path_error = np.random.normal(loc=5.0, scale=2.5)\n",
    "            headshot_rate = np.random.normal(loc=0.45, scale=0.15)\n",
    "            \n",
    "        headshot_rate = min(max(headshot_rate, 0), 1)\n",
    "        \n",
    "        data.append({\n",
    "            'time_to_damage_ms': time_to_dmg,\n",
    "            'aim_path_deviation': aim_path_error,\n",
    "            'headshot_rate': headshot_rate,\n",
    "            'is_cheater': es_cheater\n",
    "        })\n",
    "            \n",
    "    return pd.DataFrame(data)\n",
    "\n",
    "# --- 2. CLASE DEL MODELO ---\n",
    "class AntiCheatDetector:\n",
    "    def __init__(self, n_estimators: int = 100, random_state: int = 42):\n",
    "        self.pipeline = Pipeline([\n",
    "            ('scaler', StandardScaler()),\n",
    "            ('classifier', RandomForestClassifier(\n",
    "                n_estimators=n_estimators,\n",
    "                class_weight='balanced',\n",
    "                random_state=random_state,\n",
    "                n_jobs=-1\n",
    "            ))\n",
    "        ])\n",
    "        self.is_trained = False\n",
    "        self.version = \"1.0.0\"\n",
    "\n",
    "    def train(self, df: pd.DataFrame, target_col: str, feature_cols: List[str]):\n",
    "        logger.info(f\"Entrenando modelo v{self.version} con {len(df)} registros...\")\n",
    "        X = df[feature_cols]\n",
    "        y = df[target_col]\n",
    "        \n",
    "        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)\n",
    "        self.pipeline.fit(X_train, y_train)\n",
    "        self.is_trained = True\n",
    "        \n",
    "        # Validación rápida\n",
    "        score = self.pipeline.score(X_test, y_test)\n",
    "        logger.info(f\"Modelo entrenado. Accuracy en test: {score:.4f}\")\n",
    "\n",
    "    def predict_player(self, player_stats: dict) -> dict:\n",
    "        if not self.is_trained:\n",
    "            raise Exception(\"Modelo no entrenado.\")\n",
    "\n",
    "        input_df = pd.DataFrame([player_stats])\n",
    "        probability = self.pipeline.predict_proba(input_df)[0][1] # Probabilidad de ser clase 1 (Cheater)\n",
    "        \n",
    "        # Threshold estricto (85%) para evitar banear inocentes\n",
    "        is_cheater = probability > 0.85\n",
    "        \n",
    "        return {\n",
    "            \"is_cheater\": bool(is_cheater),\n",
    "            \"confidence\": round(probability, 4),\n",
    "            \"risk_level\": \"CRITICAL\" if probability > 0.95 else (\"HIGH\" if probability > 0.85 else \"LOW\")\n",
    "        }\n",
    "\n",
    "    def save(self, filepath: str):\n",
    "        joblib.dump(self.pipeline, filepath)\n",
    "        logger.info(f\"Modelo guardado en {filepath}\")\n",
    "\n",
    "    def load(self, filepath: str):\n",
    "        self.pipeline = joblib.load(filepath)\n",
    "        self.is_trained = True\n",
    "        logger.info(f\"Modelo cargado desde {filepath}\")\n",
    "\n",
    "# Si ejecutamos este archivo directamente, entrena y guarda el modelo\n",
    "if __name__ == \"__main__\":\n",
    "    detector = AntiCheatDetector()\n",
    "    df = generar_datos_jugadores(2000)\n",
    "    detector.train(df, 'is_cheater', ['time_to_damage_ms', 'aim_path_deviation', 'headshot_rate'])\n",
    "    detector.save(\"embark_model.pkl\")\n",
    "    print(\"¡Proceso de entrenamiento finalizado! Archivo .pkl generado.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "67914e7a-fb93-4fdc-877a-f3c90c8104aa",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
